# Generated by Django 5.0.4 on 2024-04-16 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('enrolled_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('content', models.CharField(max_length=150)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikers', models.ManyToManyField(related_name='disliked_newsletters', to='Base.student')),
                ('likers', models.ManyToManyField(related_name='liked_newsletters', to='Base.student')),
            ],
        ),
    ]
