# Generated by Django 5.0.4 on 2024-04-16 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_prof_profile_pic_student_profile_pic_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettre',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked_newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newslettre',
            name='likers',
            field=models.ManyToManyField(related_name='liked_newsletters', to=settings.AUTH_USER_MODEL),
        ),
    ]
