# Generated by Django 4.2.6 on 2024-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_newslettre_dislikers_alter_newslettre_likers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('Event', models.CharField(max_length=150)),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
