# Generated by Django 4.2.6 on 2024-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_ticket_event_alter_ticket_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_place/'),
        ),
        migrations.AlterField(
            model_name='newslettre',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
