# Generated by Django 5.0.4 on 2024-04-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_ticket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='images/image.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
